/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 1 looks like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="logEna"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="trgOps"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="intgPd"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="Max"
      required=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="read Log"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="SGEdit"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="ConfSG"
      nullable=""
    >
    </wizard-checkbox>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="next"
    icon="navigate_next"
    label="[wizard.title.edit]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 1 looks like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 2 looks like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="rptID"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="optFields"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="bufTime"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="trgOps"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="intgPd"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="resvTms"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="owner"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-select
      disabled=""
      label="bufMode"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        unbuffered
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        buffered
      </mwc-list-item>
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        both
      </mwc-list-item>
    </wizard-select>
    <wizard-textfield
      disabled=""
      label="maxBuf"
      nullable=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="bufConf"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxReports"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="bufReport"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="unbufReport"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="maxAttributes"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="prev"
    icon="navigate_before"
    label="[wizard.title.edit]"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="next"
    icon="navigate_next"
    label="[wizard.title.edit]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 2 looks like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 3 looks like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="appID"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="dataLabel"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="kdaParticipant"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="signature"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="encryption"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="fixedOffs"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      defaultvalue=""
      disabled=""
      label="goose"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="rGOOSE"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="goose"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="maxGOOSE"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="rGOOSE"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="gsse"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxGo"
      nullable=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="prev"
    icon="navigate_before"
    label="[wizard.title.edit]"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="next"
    icon="navigate_next"
    label="[wizard.title.edit]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 3 looks like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 4 looks like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="svID"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="optFields"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="smpRate"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="nofASDU"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="samplesPerSec"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="synchSrcId"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="pdcTimeStamp"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="kdaParticipant"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="signature"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="encryption"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="SmpRate"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="SamplesPerSec"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="SecPerSamples"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-select
      disabled=""
      label="delivery"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        unicast
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        multicast
      </mwc-list-item>
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        both
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="deliveryConf"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="sv"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="rSV"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="sv"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="maxSMV"
      nullable=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="rSV"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxSv"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="prev"
    icon="navigate_before"
    label="[wizard.title.edit]"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 4 looks like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 1 should look like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="logEna"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="trgOps"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="intgPd"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="Max"
      required=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="read Log"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="SGEdit"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="ConfSG"
      nullable=""
    >
    </wizard-checkbox>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="next"
    icon="navigate_next"
    label="[wizard.title.edit]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 1 should look like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 2 should look like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="rptID"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="optFields"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="bufTime"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="trgOps"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="intgPd"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="resvTms"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="owner"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-select
      disabled=""
      label="bufMode"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        unbuffered
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        buffered
      </mwc-list-item>
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        both
      </mwc-list-item>
    </wizard-select>
    <wizard-textfield
      disabled=""
      label="maxBuf"
      nullable=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="bufConf"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxReports"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="bufReport"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="unbufReport"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="maxAttributes"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="prev"
    icon="navigate_before"
    label="[wizard.title.edit]"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="next"
    icon="navigate_next"
    label="[wizard.title.edit]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 2 should look like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 3 should look like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="appID"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="dataLabel"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="kdaParticipant"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="signature"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="encryption"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="fixedOffs"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      defaultvalue=""
      disabled=""
      label="goose"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="rGOOSE"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="goose"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="maxGOOSE"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="rGOOSE"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="gsse"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxGo"
      nullable=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="prev"
    icon="navigate_before"
    label="[wizard.title.edit]"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="next"
    icon="navigate_next"
    label="[wizard.title.edit]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 3 should look like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 4 should look like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="svID"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="optFields"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="smpRate"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="nofASDU"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="samplesPerSec"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="synchSrcId"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="pdcTimeStamp"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="kdaParticipant"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="signature"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="encryption"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="SmpRate"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="SamplesPerSec"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="SecPerSamples"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-select
      disabled=""
      label="delivery"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        unicast
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        multicast
      </mwc-list-item>
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        both
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="deliveryConf"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="sv"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="rSV"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="sv"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="maxSMV"
      nullable=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="rSV"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxSv"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="prev"
    icon="navigate_before"
    label="[wizard.title.edit]"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 4 should look like snapshot */

snapshots["Wizards for SCL element Services AccessPoint wizards for Scl element Services should look like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="appID"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="dataLabel"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="kdaParticipant"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="signature"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="encryption"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="fixedOffs"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      defaultvalue=""
      disabled=""
      label="goose"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="rGOOSE"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="goose"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="maxGOOSE"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="rGOOSE"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="gsse"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxGo"
      nullable=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services AccessPoint wizards for Scl element Services should look like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 5 should look like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-select
      disabled=""
      label="cbName"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="datSet"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="svID"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="optFields"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="smpRate"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Dyn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-select
      disabled=""
      label="nofASDU"
      nullable=""
    >
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        Conf
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        Fix
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="samplesPerSec"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="synchSrcId"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="pdcTimeStamp"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="kdaParticipant"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="signature"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="encryption"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="SmpRate"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="SamplesPerSec"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      label="SecPerSamples"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-select
      disabled=""
      label="delivery"
      nullable=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        unicast
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
      >
        multicast
      </mwc-list-item>
      <mwc-list-item
        activated=""
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
      >
        both
      </mwc-list-item>
    </wizard-select>
    <wizard-checkbox
      disabled=""
      label="deliveryConf"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="sv"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="rSV"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="sv"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      disabled=""
      label="maxSMV"
      nullable=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="rSV"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxSv"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="prev"
    icon="navigate_before"
    label="[wizard.title.edit]"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="next"
    icon="navigate_next"
    label="[wizard.title.edit]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 5 should look like snapshot */

snapshots["Wizards for SCL element Services define a Services wizards  Wizard 6 should look like snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.edit]"
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
    >
    </wizard-textfield>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="GetDirectory"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="GetDataObjectDefinition"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="DataObjectDirectory"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="GetDataSetValue"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="SetDataSetValue"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="SetDataSetDirectory"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="ReadWrite"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="ConfLdName"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="supportsLdName"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="maxAttributes"
      nullable=""
    >
    </wizard-textfield>
    <wizard-checkbox
      disabled=""
      label="TimerActivatedControl"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="GetCBValues"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      disabled=""
      label="GSEDir"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-checkbox
      disabled=""
      label="setToRO"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-divider>
    </wizard-divider>
    <wizard-textfield
      disabled=""
      label="max"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="prev"
    icon="navigate_before"
    label="[wizard.title.edit]"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for SCL element Services define a Services wizards  Wizard 6 should look like snapshot */

