/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["web component rendering EqFunction element with complete attribute set and existing children looks like the latest snapshot"] = 
`<action-pane
  highlighted=""
  icon="functions"
  label="myEqFuncQA1 - funcForQA1 (eqFuncType)"
  secondary=""
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqSubFunction"
      >
        <span>
          EqSubFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <eq-sub-function-editor>
  </eq-sub-function-editor>
</action-pane>
`;
/* end snapshot web component rendering EqFunction element with complete attribute set and existing children looks like the latest snapshot */

snapshots["web component rendering EqFunction element with missing desc and type attribute looks like the latest snapshot"] = 
`<action-pane
  highlighted=""
  icon="functions"
  label="myEqFuncPtr2"
  secondary=""
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqSubFunction"
      >
        <span>
          EqSubFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <eq-sub-function-editor>
  </eq-sub-function-editor>
</action-pane>
`;
/* end snapshot web component rendering EqFunction element with missing desc and type attribute looks like the latest snapshot */

snapshots["web component rendering EqFunction element with existing LNode children looks like the latest snapshot"] = 
`<action-pane
  highlighted=""
  icon="functions"
  label="myEqFuncQB1"
  secondary=""
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqSubFunction"
      >
        <span>
          EqSubFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <div class="container lnode">
    <l-node-editor>
    </l-node-editor>
    <l-node-editor>
    </l-node-editor>
    <l-node-editor>
    </l-node-editor>
  </div>
</action-pane>
`;
/* end snapshot web component rendering EqFunction element with existing LNode children looks like the latest snapshot */

snapshots["web component rendering EqFunction element with general-equipment children with showfunctions false looks like the latest snapshot"] = 
`<action-pane
  highlighted=""
  icon="functions"
  label="genEqFunc"
  secondary=""
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqSubFunction"
      >
        <span>
          EqSubFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
</action-pane>
`;
/* end snapshot web component rendering EqFunction element with general-equipment children with showfunctions false looks like the latest snapshot */

snapshots["web component rendering EqFunction element with general-equipment children with showfunctions true looks like the latest snapshot"] = 
`<action-pane
  highlighted=""
  icon="functions"
  label="genEqFunc"
  secondary=""
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqSubFunction"
      >
        <span>
          EqSubFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
</action-pane>
`;
/* end snapshot web component rendering EqFunction element with general-equipment children with showfunctions true looks like the latest snapshot */

