<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SCL xmlns:compas="https://www.lfenergy.org/compas/v1" xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B" release="4">
  <Private type="compas_scl">
    <compas:SclFileType>CID</compas:SclFileType>
  </Private>
  <Header id="380b5e70-4753-4b59-b5b4-d51ceb26a30c" version="3.0.0" revision="Revision" toolID="toolID" nameStructure="IEDName"/>
</SCL>
