<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SCL xmlns:compas="https://www.lfenergy.org/compas/extension/v1" xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B" release="4">
  <Private type="compas_scl">
    <compas:SclName>existing</compas:SclName>
    <compas:SclFileType>CID</compas:SclFileType>
    <compas:Labels>
      <compas:Label>Label1</compas:Label>
    </compas:Labels>
  </Private>
  <Header id="id-value" version="3.0.0" revision="Revision" toolID="toolID" nameStructure="IEDName"/>
</SCL>
