<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SCL xmlns="http://www.iec.ch/61850/2003/SCL" release="4" revision="B" version="2007">
  <Header id="40cf9d4d-19b1-4d24-9faa-0afa26ded001" revision="" version="1.0.0">
    <History>
      <Hitem revision="" version="0.0.1" what="SCD created from CIM File(s): some-cim-file.xml" when="2021-09-14T10:51:38Z" who="Test User 1"/>
      <Hitem revision="" version="1.0.0" what="SCD created, Nice history test 1" when="2021-09-14T10:52:28Z" who="Test User 1"/>
      <Hitem revision="" version="1.1.0" what="SCD updated, Nice history test 2" when="" who="Test User 1"/>
      <Hitem revision="" version="1.2.0" what="SCD updated, Nice history test 3" when="invalid" who="Test User 1" why="Small correction in substation"/>
      <Hitem revision="" version="1.2.0" what="SCD updated, Nice history test 4" why="Small correction in substation"/>
      <Hitem revision="" version="1.2.0" what="SCD updated, Nice history test 5" />
      <Hitem revision="" version="1.2.0" who="Test User 1" why="Small correction in substation"/>
    </History>
  </Header>
</SCL>
