/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["DAType wizards defines a createDATypeWizard looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[datype.wizard.title.add]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <mwc-select
      fixedmenuposition=""
      helper="Default enumerations"
      icon="playlist_add_check"
      label="values"
      outlined=""
    >
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="0"
        value="OpenSCD_AnalogueValue_FLOAT32"
      >
        <span>
          AnalogueValue_FLOAT32
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_AnalogueValue_INT32"
      >
        <span>
          AnalogueValue_INT32
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Cancel_SPC"
      >
        <span>
          Cancel_SPC
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Cancel_Dbpos"
      >
        <span>
          Cancel_Dbpos
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Cancel_FLOAT32"
      >
        <span>
          Cancel_FLOAT32
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Cancel_StepControlKind"
      >
        <span>
          Cancel_StepControlKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Cancel_BehaviourModeKind"
      >
        <span>
          Cancel_BehaviourModeKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Cancel_INT8"
      >
        <span>
          Cancel_INT8
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_CalendarTime"
      >
        <span>
          CalendarTime
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Cell2D"
      >
        <span>
          Cell2D
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Cell1D"
      >
        <span>
          Cell1D
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_OperSBOw_SPC"
      >
        <span>
          OperSBOw_SPC
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_OperSBOw_Dbpos"
      >
        <span>
          OperSBOw_Dbpos
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_OperSBOw_FLOAT32"
      >
        <span>
          OperSBOw_FLOAT32
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_OperSBOw_StepControlKind"
      >
        <span>
          OperSBOw_StepControlKind
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_OperSBOw_BehaviourModeKind"
      >
        <span>
          OperSBOw_BehaviourModeKind
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_OperSBOw_INT8"
      >
        <span>
          OperSBOw_INT8
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Originator"
      >
        <span>
          Originator
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Point3D"
      >
        <span>
          Point3D
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Point2D"
      >
        <span>
          Point2D
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_PulseConfig"
      >
        <span>
          PulseConfig
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_RangeConfig"
      >
        <span>
          RangeConfig
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ScaledValueConfig_AmpSv"
      >
        <span>
          ScaledValueConfig_AmpSv
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ScaledValueConfig_VolSv"
      >
        <span>
          ScaledValueConfig_VolSv
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Unit_A"
      >
        <span>
          Unit_A
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Unit_V"
      >
        <span>
          Unit_V
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Unit_Hz"
      >
        <span>
          Unit_Hz
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ValWithTrans_wo_transInd"
      >
        <span>
          ValWithTrans_wo_transInd
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Vector_I_w_Ang"
      >
        <span>
          Vector_I_w_Ang
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Vector_F_w_Ang"
      >
        <span>
          Vector_F_w_Ang
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Vector_I_wo_Ang"
      >
        <span>
          Vector_I_wo_Ang
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_Vector_F_wo_Ang"
      >
        <span>
          Vector_F_wo_Ang
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ScaledValueConfig"
      >
        <span>
          ScaledValueConfig
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Unit"
      >
        <span>
          Unit
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ValWithTrans"
      >
        <span>
          ValWithTrans
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
    </mwc-select>
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.id]"
      label="id"
      maxlength="255"
      minlength="1"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="add"
    label="[add]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot DAType wizards defines a createDATypeWizard looks like the latest snapshot */

snapshots["DAType wizards defines a dATypeWizard looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[datype.wizard.title.edit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 48px)"
>
  <nav>
    <mwc-icon-button icon="more_vert">
    </mwc-icon-button>
    <mwc-menu
      class="actions-menu"
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
      >
        <span>
          [remove]
        </span>
        <mwc-icon slot="graphic">
          delete
        </mwc-icon>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
      >
        <span>
          [scl.DA]
        </span>
        <mwc-icon slot="graphic">
          playlist_add
        </mwc-icon>
      </mwc-list-item>
    </mwc-menu>
  </nav>
  <div id="wizard-content">
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.id]"
      label="id"
      maxlength="127"
      minlength="1"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
    <mwc-list style="margin-top: 0px;">
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="0"
        twoline=""
        value="#Dummy.LLN0.Mod.SBOw>ctlVal"
      >
        <span>
          ctlVal
        </span>
        <span slot="secondary">
          #Dummy_Beh
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod.SBOw>origin"
      >
        <span>
          origin
        </span>
        <span slot="secondary">
          #Dummy_origin
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod.SBOw>ctlNum"
      >
        <span>
          ctlNum
        </span>
        <span slot="secondary">
          INT8U
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod.SBOw>T"
      >
        <span>
          T
        </span>
        <span slot="secondary">
          Timestamp
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod.SBOw>Test"
      >
        <span>
          Test
        </span>
        <span slot="secondary">
          BOOLEAN
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod.SBOw>Check"
      >
        <span>
          Check
        </span>
        <span slot="secondary">
          Check
        </span>
      </mwc-list-item>
    </mwc-list>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon=""
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot DAType wizards defines a dATypeWizard looks like the latest snapshot */

