/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["EnumType wizards defines a createEnumTypeWizard looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[enum.wizard.title.add]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <mwc-select
      helper="Default enumerations"
      icon="playlist_add_check"
      label="values"
      outlined=""
      style="--mdc-menu-max-height: 196px;"
    >
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="0"
        value="BehaviourModeKind"
      >
        <span>
          BehaviourModeKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="CtlModelKind"
      >
        <span>
          CtlModelKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_StatusOnly"
      >
        <span>
          OpenSCD_StatusOnly
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OriginatorCategoryKind"
      >
        <span>
          OriginatorCategoryKind
        </span>
        <span slot="meta">
          9
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="MultiplierKind"
      >
        <span>
          MultiplierKind
        </span>
        <span slot="meta">
          21
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="AngleReferenceKind"
      >
        <span>
          AngleReferenceKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="CurveCharKind"
      >
        <span>
          CurveCharKind
        </span>
        <span slot="meta">
          17
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="FaultDirectionKind"
      >
        <span>
          FaultDirectionKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="HvReferenceKind"
      >
        <span>
          HvReferenceKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="MonthKind"
      >
        <span>
          MonthKind
        </span>
        <span slot="meta">
          13
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OccurrenceKind"
      >
        <span>
          OccurrenceKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OutputSignalKind"
      >
        <span>
          OutputSignalKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="PeriodKind"
      >
        <span>
          PeriodKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="PhaseAngleReferenceKind"
      >
        <span>
          PhaseAngleReferenceKind
        </span>
        <span slot="meta">
          12
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="PhaseFaultDirectionKind"
      >
        <span>
          PhaseFaultDirectionKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="PhaseReferenceKind"
      >
        <span>
          PhaseReferenceKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="RangeKind"
      >
        <span>
          RangeKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SIUnitKind"
      >
        <span>
          SIUnitKind
        </span>
        <span slot="meta">
          77
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SboClassKind"
      >
        <span>
          SboClassKind
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SequenceKind"
      >
        <span>
          SequenceKind
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SeverityKind"
      >
        <span>
          SeverityKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="WeekdayKind"
      >
        <span>
          WeekdayKind
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="AdjustmentKind"
      >
        <span>
          AdjustmentKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="AffectedPhasesKind"
      >
        <span>
          AffectedPhasesKind
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="AutoReclosingKind"
      >
        <span>
          AutoReclosingKind
        </span>
        <span slot="meta">
          12
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="BreakerOpCapabilityKind"
      >
        <span>
          BreakerOpCapabilityKind
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="CalcIntervalKind"
      >
        <span>
          CalcIntervalKind
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="CalcMethodKind"
      >
        <span>
          CalcMethodKind
        </span>
        <span slot="meta">
          13
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="CalcModeKind"
      >
        <span>
          CalcModeKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ClockSourceKind"
      >
        <span>
          ClockSourceKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ClockSyncKind"
      >
        <span>
          ClockSyncKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ClockSyncLockingKind"
      >
        <span>
          ClockSyncLockingKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="DirectionModeKind"
      >
        <span>
          DirectionModeKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="FailureDetectionKind"
      >
        <span>
          FailureDetectionKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="FaultLoopKind"
      >
        <span>
          FaultLoopKind
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="FaultMeasuredValueTypeKind"
      >
        <span>
          FaultMeasuredValueTypeKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="FilterFunctionKind"
      >
        <span>
          FilterFunctionKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="FuseFunctionKind"
      >
        <span>
          FuseFunctionKind
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="HealthKind"
      >
        <span>
          HealthKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="InstrumentTransformerMeasurementRatingKind"
      >
        <span>
          InstrumentTransformerMeasurementRatingKind
        </span>
        <span slot="meta">
          9
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="InstrumentTransformerProtectionRatingKind"
      >
        <span>
          InstrumentTransformerProtectionRatingKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="LeapSecondKind"
      >
        <span>
          LeapSecondKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="LevelTriggerModeKind"
      >
        <span>
          LevelTriggerModeKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="LiveDeadModeKind"
      >
        <span>
          LiveDeadModeKind
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="MaterialKind"
      >
        <span>
          MaterialKind
        </span>
        <span slot="meta">
          11
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="MaterialStateKind"
      >
        <span>
          MaterialStateKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="PFSignKind"
      >
        <span>
          PFSignKind
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="PIDAlgorithmKind"
      >
        <span>
          PIDAlgorithmKind
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="POWSwitchingCapabilityKind"
      >
        <span>
          POWSwitchingCapabilityKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ParallelCoilModeKind"
      >
        <span>
          ParallelCoilModeKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ParallelCtrlModeKind"
      >
        <span>
          ParallelCtrlModeKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ParallelTransfModeKind"
      >
        <span>
          ParallelTransfModeKind
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="PolarizingQuantityKind"
      >
        <span>
          PolarizingQuantityKind
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="RecordingModeKind"
      >
        <span>
          RecordingModeKind
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="RectifierControlModeKind"
      >
        <span>
          RectifierControlModeKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ResetCurveKind"
      >
        <span>
          ResetCurveKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="RestraintModeKind"
      >
        <span>
          RestraintModeKind
        </span>
        <span slot="meta">
          9
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="RetripModeKind"
      >
        <span>
          RetripModeKind
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="RotatingMachineStateKind"
      >
        <span>
          RotatingMachineStateKind
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="RotationalDirectionKind"
      >
        <span>
          RotationalDirectionKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="RotorThermalStateKind"
      >
        <span>
          RotorThermalStateKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SOFEnablingModeKind"
      >
        <span>
          SOFEnablingModeKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SOFOperationModeKind"
      >
        <span>
          SOFOperationModeKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="STotalCalcMethodKind"
      >
        <span>
          STotalCalcMethodKind
        </span>
        <span slot="meta">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ScheduleEnablingErrorKind"
      >
        <span>
          ScheduleEnablingErrorKind
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="ScheduleStateKind"
      >
        <span>
          ScheduleStateKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SetpointEndKind"
      >
        <span>
          SetpointEndKind
        </span>
        <span slot="meta">
          16
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="StageControlKind"
      >
        <span>
          StageControlKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SwitchFunctionKind"
      >
        <span>
          SwitchFunctionKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SwitchingCapabilityKind"
      >
        <span>
          SwitchingCapabilityKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="SynchOperationModeKind"
      >
        <span>
          SynchOperationModeKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="TankFillKind"
      >
        <span>
          TankFillKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="TransientPerformanceClassKind"
      >
        <span>
          TransientPerformanceClassKind
        </span>
        <span slot="meta">
          9
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="TpcAppModeKind"
      >
        <span>
          TpcAppModeKind
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="TriggerSourceKind"
      >
        <span>
          TriggerSourceKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="TripBehaviourKind"
      >
        <span>
          TripBehaviourKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="TripModeKind"
      >
        <span>
          TripModeKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="TuningKind"
      >
        <span>
          TuningKind
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="UnbalanceDetectionKind"
      >
        <span>
          UnbalanceDetectionKind
        </span>
        <span slot="meta">
          6
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="UnblockModeKind"
      >
        <span>
          UnblockModeKind
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="VoltInterruptDetectionKind"
      >
        <span>
          VoltInterruptDetectionKind
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="WeakEndInfeedModeKind"
      >
        <span>
          WeakEndInfeedModeKind
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
    </mwc-select>
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.id]"
      label="id"
      maxlength="127"
      minlength="1"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="add"
    label="[add]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot EnumType wizards defines a createEnumTypeWizard looks like the latest snapshot */

snapshots["EnumType wizards defines an eNumTypeEditWizard looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[enum.wizard.title.edit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 48px)"
>
  <nav>
    <mwc-icon-button icon="more_vert">
    </mwc-icon-button>
    <mwc-menu
      class="actions-menu"
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
      >
        <span>
          [remove]
        </span>
        <mwc-icon slot="graphic">
          delete
        </mwc-icon>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
      >
        <span>
          [scl.EnumVal]
        </span>
        <mwc-icon slot="graphic">
          playlist_add
        </mwc-icon>
      </mwc-list-item>
    </mwc-menu>
  </nav>
  <div id="wizard-content">
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.id]"
      label="id"
      maxlength="127"
      minlength="1"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
    <mwc-list style="margin-top: 0px;">
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        tabindex="0"
        value="#Dummy_ctlModel>0"
      >
        <span>
          status-only
        </span>
        <span slot="graphic">
          0
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        tabindex="-1"
        value="#Dummy_ctlModel>1"
      >
        <span>
          direct-with-normal-security
        </span>
        <span slot="graphic">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        tabindex="-1"
        value="#Dummy_ctlModel>2"
      >
        <span>
          sbo-with-normal-security
        </span>
        <span slot="graphic">
          2
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        tabindex="-1"
        value="#Dummy_ctlModel>3"
      >
        <span>
          direct-with-enhanced-security
        </span>
        <span slot="graphic">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        tabindex="-1"
        value="#Dummy_ctlModel>4"
      >
        <span>
          sbo-with-enhanced-security
        </span>
        <span slot="graphic">
          4
        </span>
      </mwc-list-item>
    </mwc-list>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon=""
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot EnumType wizards defines an eNumTypeEditWizard looks like the latest snapshot */

snapshots["EnumType wizards defines a eNumValWizard to edit an existing EnumVal looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[enum-val.wizard.title.edit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 48px)"
>
  <nav>
    <mwc-icon-button icon="more_vert">
    </mwc-icon-button>
    <mwc-menu
      class="actions-menu"
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
      >
        <span>
          [remove]
        </span>
        <mwc-icon slot="graphic">
          delete
        </mwc-icon>
      </mwc-list-item>
    </mwc-menu>
  </nav>
  <div id="wizard-content">
    <wizard-textfield
      helper="[scl.ord]"
      label="ord"
      required=""
      type="number"
    >
    </wizard-textfield>
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.value]"
      label="value"
      pattern="([ -~]|[]|[ -퟿]|[-�])*"
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      id="evDesc"
      label="desc"
      nullable=""
      pattern="([ -~]|[]|[ -퟿]|[-�])*"
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon=""
    label="Save"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot EnumType wizards defines a eNumValWizard to edit an existing EnumVal looks like the latest snapshot */

snapshots["EnumType wizards defines a eNumValWizard to create a new EnumVal element looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[enum-val.wizard.title.add]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-textfield
      helper="[scl.ord]"
      label="ord"
      required=""
      type="number"
    >
    </wizard-textfield>
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.value]"
      label="value"
      pattern="([ -~]|[]|[ -퟿]|[-�])*"
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      id="evDesc"
      label="desc"
      nullable=""
      pattern="([ -~]|[]|[ -퟿]|[-�])*"
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon=""
    label="Save"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot EnumType wizards defines a eNumValWizard to create a new EnumVal element looks like the latest snapshot */

