/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["Editor for ReportControl element and its direct children with valid ReportControl looks like the latest snapshot"] = 
`<h2 style="display: flex;">
  <div style="flex:auto">
    <div>
      ReportControl
    </div>
    <div class="headersubtitle">
      IED2>>CBSW> XSWI 1>ReportCb
    </div>
  </div>
</h2>
<div class="parentcontent">
  <div class="content">
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.name]"
      label="name"
      maxlength="32"
      pattern="[A-Za-z][0-9,A-Z,a-z_]*"
      required=""
      validationmessage="[textfield.required]"
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
    <wizard-checkbox
      helper="[scl.buffered]"
      label="buffered"
    >
    </wizard-checkbox>
    <wizard-textfield
      helper="[report.rptID]"
      label="rptID"
      nullable=""
      required=""
    >
    </wizard-textfield>
    <wizard-checkbox
      helper="[scl.indexed]"
      label="indexed"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-textfield
      helper="[scl.maxReport]"
      label="max Clients"
      nullable=""
      suffix="#"
      type="number"
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[scl.bufTime]"
      label="bufTime"
      min="0"
      nullable=""
      required=""
      suffix="ms"
      type="number"
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[scl.intgPd]"
      label="intgPd"
      min="0"
      nullable=""
      required=""
      suffix="ms"
      type="number"
    >
    </wizard-textfield>
  </div>
  <div class="content">
    <h3>
      Trigger Options
    </h3>
    <wizard-checkbox
      helper="[scl.dchg]"
      label="dchg"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.qchg]"
      label="qchg"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.dupd]"
      label="dupd"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.period]"
      label="period"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.gi]"
      label="gi"
      nullable=""
    >
    </wizard-checkbox>
    <h3>
      Optional Fields
    </h3>
    <wizard-checkbox
      helper="[scl.seqNum]"
      label="seqNum"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.timeStamp]"
      label="timeStamp"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.dataSet]"
      label="dataSet"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.reasonCode]"
      label="reasonCode"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.dataRef]"
      label="dataRef"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.entryID]"
      label="entryID"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.configRef]"
      label="configRef"
      nullable=""
    >
    </wizard-checkbox>
    <wizard-checkbox
      helper="[scl.bufOvfl]"
      label="bufOvfl"
      nullable=""
    >
    </wizard-checkbox>
  </div>
</div>
`;
/* end snapshot Editor for ReportControl element and its direct children with valid ReportControl looks like the latest snapshot */

