
export const officialPlugins = [
  {
    name: 'IED',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/IED.js",
    icon: 'developer_board',
    default: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Substation',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/Substation.js",
    icon: 'margin',
    default: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Single Line Diagram',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/SingleLineDiagram.js",
    icon: 'edit',
    default: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Message Binding (GOOSE)',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/GooseSubscriberMessageBinding.js",
    icon: 'link',
    default: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Data Binding (GOOSE)',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/GooseSubscriberDataBinding.js",
    icon: 'link',
    default: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Later Binding (GOOSE)',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/GooseSubscriberLaterBinding.js",
    icon: 'link',
    default: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Message Binding (SMV)',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/SMVSubscriberMessageBinding.js",
    icon: 'link',
    default: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Data Binding (SMV)',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/SMVSubscriberDataBinding.js",
    icon: 'link',
    default: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Subscriber Later Binding (SMV)',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/SMVSubscriberLaterBinding.js",
    icon: 'link',
    default: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Communication',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/Communication.js",
    icon: 'settings_ethernet',
    default: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: '104',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/Protocol104.js",
    icon: 'settings_ethernet',
    default: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Templates',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/Templates.js",
    icon: 'copy_all',
    default: true,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Publisher',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/Publisher.js",
    icon: 'publish',
    default: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Cleanup',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/editors/Cleanup.js",
    icon: 'cleaning_services',
    default: false,
    kind: 'editor',
    requireDoc: true,
  },
  {
    name: 'Open project',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/OpenProject.js",
    icon: 'folder_open',
    default: true,
    kind: 'menu',
    requireDoc: false,
    position: 'top',
  },
  {
    name: 'New project',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/NewProject.js",
    icon: 'create_new_folder',
    default: true,
    kind: 'menu',
    requireDoc: false,
    position: 'top',
  },
  {
    name: 'Save project',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/SaveProject.js",
    icon: 'save',
    default: true,
    kind: 'menu',
    requireDoc: true,
    position: 'top',
  },
  {
    name: 'Validate Schema',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/validators/ValidateSchema.js",
    icon: 'rule_folder',
    default: true,
    kind: 'validator',
  },
  {
    name: 'Validate Templates',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/validators/ValidateTemplates.js",
    icon: 'rule_folder',
    default: true,
    kind: 'validator',
  },
  {
    name: 'Import IEDs',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/ImportIEDs.js",
    icon: 'snippet_folder',
    default: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Create Virtual IED',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/VirtualTemplateIED.js",
    icon: 'developer_board',
    default: false,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Subscriber Update',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/SubscriberInfo.js",
    default: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Update desc (ABB)',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/UpdateDescriptionABB.js",
    default: false,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Update desc (SEL)',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/UpdateDescriptionSEL.js",
    default: false,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Merge Project',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/Merge.js",
    icon: 'merge_type',
    default: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Update Substation',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/UpdateSubstation.js",
    icon: 'merge_type',
    default: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Compare IED',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/CompareIED.js",
    icon: 'compare_arrows',
    default: true,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
  {
    name: 'Show SCL History',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/SclHistory.js",
    icon: 'history_toggle_off',
    default: true,
    kind: 'menu',
    requireDoc: true,
    position: 'bottom',
  },
  {
    name: 'Help',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/Help.js",
    icon: 'help',
    default: true,
    kind: 'menu',
    requireDoc: false,
    position: 'bottom',
  },
  {
    name: 'Export Communication Section',
    src: "https://openscd.github.io/oscd-official-plugins/plugins/menu/ExportCommunication.js",
    icon: 'sim_card_download',
    default: false,
    kind: 'menu',
    requireDoc: true,
    position: 'middle',
  },
];
