/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["powertransformer-editor rendered as action icon looks like the latest snapshot"] = 
`<action-icon
  label="TA1"
  tabindex="0"
>
  <mwc-icon slot="icon">
  </mwc-icon>
  <mwc-fab
    class="edit"
    icon="edit"
    mini=""
    slot="action"
  >
  </mwc-fab>
  <mwc-fab
    icon="delete"
    mini=""
    slot="action"
  >
  </mwc-fab>
  <mwc-fab
    icon="forward"
    mini=""
    slot="action"
  >
  </mwc-fab>
  <mwc-fab
    icon="account_tree"
    mini=""
    slot="action"
  >
  </mwc-fab>
</action-icon>
`;
/* end snapshot powertransformer-editor rendered as action icon looks like the latest snapshot */

snapshots["powertransformer-editor rendered as action pane looks like the latest snapshot"] = 
`<action-pane
  label="TA1"
  tabindex="0"
>
  <mwc-icon
    slot="icon"
    style="width:24px;height:24px"
  >
  </mwc-icon>
  <abbr
    slot="action"
    title="[lnode.tooltip]"
  >
    <mwc-icon-button
      icon="account_tree"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button
      icon="edit"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[move]"
  >
    <mwc-icon-button
      icon="forward"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button
      icon="delete"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="TransformerWinding"
      >
        <span>
          TransformerWinding
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="SubEquipment"
      >
        <span>
          SubEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqFunction"
      >
        <span>
          EqFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <div class="container">
    <transformer-winding-editor showfunctions="">
    </transformer-winding-editor>
    <transformer-winding-editor showfunctions="">
    </transformer-winding-editor>
  </div>
</action-pane>
`;
/* end snapshot powertransformer-editor rendered as action pane looks like the latest snapshot */

snapshots["powertransformer-editor rendered as action pane with EqFunction children looks like the latest snapshot"] = 
`<action-pane
  label="myPtr2"
  tabindex="0"
>
  <mwc-icon
    slot="icon"
    style="width:24px;height:24px"
  >
  </mwc-icon>
  <abbr
    slot="action"
    title="[lnode.tooltip]"
  >
    <mwc-icon-button
      icon="account_tree"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button
      icon="edit"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[move]"
  >
    <mwc-icon-button
      icon="forward"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button
      icon="delete"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="TransformerWinding"
      >
        <span>
          TransformerWinding
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="SubEquipment"
      >
        <span>
          SubEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqFunction"
      >
        <span>
          EqFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <eq-function-editor showfunctions="">
  </eq-function-editor>
</action-pane>
`;
/* end snapshot powertransformer-editor rendered as action pane with EqFunction children looks like the latest snapshot */

snapshots["powertransformer-editor rendered as action pane with LNode children looks like the latest snapshot"] = 
`<action-pane
  label="myPtr1"
  tabindex="0"
>
  <mwc-icon
    slot="icon"
    style="width:24px;height:24px"
  >
  </mwc-icon>
  <abbr
    slot="action"
    title="[lnode.tooltip]"
  >
    <mwc-icon-button
      icon="account_tree"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button
      icon="edit"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[move]"
  >
    <mwc-icon-button
      icon="forward"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button
      icon="delete"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="TransformerWinding"
      >
        <span>
          TransformerWinding
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="SubEquipment"
      >
        <span>
          SubEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqFunction"
      >
        <span>
          EqFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <div class="container lnode">
    <l-node-editor>
    </l-node-editor>
  </div>
</action-pane>
`;
/* end snapshot powertransformer-editor rendered as action pane with LNode children looks like the latest snapshot */

snapshots["powertransformer-editor rendered as action pane with SubEquipment children looks like the latest snapshot"] = 
`<action-pane
  label="pTrans"
  tabindex="0"
>
  <mwc-icon
    slot="icon"
    style="width:24px;height:24px"
  >
  </mwc-icon>
  <abbr
    slot="action"
    title="[lnode.tooltip]"
  >
    <mwc-icon-button
      icon="account_tree"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button
      icon="edit"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[move]"
  >
    <mwc-icon-button
      icon="forward"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button
      icon="delete"
      mini=""
      slot="action"
    >
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="TransformerWinding"
      >
        <span>
          TransformerWinding
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="SubEquipment"
      >
        <span>
          SubEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="EqFunction"
      >
        <span>
          EqFunction
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <sub-equipment-editor>
  </sub-equipment-editor>
  <sub-equipment-editor>
  </sub-equipment-editor>
  <sub-equipment-editor>
  </sub-equipment-editor>
</action-pane>
`;
/* end snapshot powertransformer-editor rendered as action pane with SubEquipment children looks like the latest snapshot */

