/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["DOType wizards defines a createDOTypeWizard looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[dotype.wizard.title.add]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <mwc-select
      fixedmenuposition=""
      helper="[dotype.wizard.enums]"
      icon="playlist_add_check"
      label="values"
      outlined=""
    >
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="0"
        value="OpenSCD_ACD_general"
      >
        <span>
          ACD_general
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ACD_threephase"
      >
        <span>
          ACD_threephase
        </span>
        <span slot="meta">
          10
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ACT_general_control"
      >
        <span>
          ACT_general_control
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ACT_threephase_control"
      >
        <span>
          ACT_threephase_control
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ACT_general"
      >
        <span>
          ACT_general
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_APC_VolSpt_ATCC"
      >
        <span>
          APC_VolSpt_ATCC
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ASG_ATrg_TCTR"
      >
        <span>
          ASG_ATrg_TCTR
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ASG_HzRtg_TCTR"
      >
        <span>
          ASG_HzRtg_TCTR
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ASG_VRtg_TVTR"
      >
        <span>
          ASG_VRtg_TVTR
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_BAC_BndCtrChg_ATCC"
      >
        <span>
          BAC_BndCtrChg_ATCC
        </span>
        <span slot="meta">
          9
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_BSC_TapChg_ATCC"
      >
        <span>
          BSC_TapChg_ATCC
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_BSC_TapChg_YLTC"
      >
        <span>
          BSC_TapChg_YLTC
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_CMV_db_i_MagAndAng"
      >
        <span>
          CMV_db_i_MagAndAng
        </span>
        <span slot="meta">
          13
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_DEL"
      >
        <span>
          DEL
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_DEL_wRef"
      >
        <span>
          DEL_wRef
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_DPL"
      >
        <span>
          DPL
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_DPC_statusonly"
      >
        <span>
          DPC_statusonly
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_DPC"
      >
        <span>
          DPC
        </span>
        <span slot="meta">
          11
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_DPSsimple"
      >
        <span>
          DPSsimple
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ENS_Beh"
      >
        <span>
          ENS_Beh
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ENC_Mod"
      >
        <span>
          ENC_Mod
        </span>
        <span slot="meta">
          10
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ENC_Mod_statusonly"
      >
        <span>
          ENC_Mod_statusonly
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ENS_Health"
      >
        <span>
          ENS_Health
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ENS_SwTyp"
      >
        <span>
          ENS_SwTyp
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_INS_simple"
      >
        <span>
          INS_simple
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ISC_TapPos_ATCC"
      >
        <span>
          ISC_TapPos_ATCC
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ISC_TapPos_YLTC"
      >
        <span>
          ISC_TapPos_YLTC
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_LPL_LD"
      >
        <span>
          LPL_LD
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_LPL_noLD"
      >
        <span>
          LPL_noLD
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_MV_db_int"
      >
        <span>
          MV_db_int
        </span>
        <span slot="meta">
          9
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_MV_int"
      >
        <span>
          MV_int
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_MV_db_float"
      >
        <span>
          MV_db_float
        </span>
        <span slot="meta">
          8
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_MV_float"
      >
        <span>
          MV_float
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_ORG_GrRef"
      >
        <span>
          ORG_GrRef
        </span>
        <span slot="meta">
          1
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_SAV_AmpSv_TCTR"
      >
        <span>
          SAV_AmpSv_TCTR
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_SAV_VolSv_TVTR"
      >
        <span>
          SAV_VolSv_TVTR
        </span>
        <span slot="meta">
          5
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_SPC_statusonly"
      >
        <span>
          SPC_statusonly
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_SPC_Auto_ATCC"
      >
        <span>
          SPC_Auto_ATCC
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_SPC_LocSta"
      >
        <span>
          SPC_LocSta
        </span>
        <span slot="meta">
          7
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_SPS_simple"
      >
        <span>
          SPS_simple
        </span>
        <span slot="meta">
          4
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        hasmeta=""
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="OpenSCD_WYE_phases"
      >
        <span>
          WYE_phases
        </span>
        <span slot="meta">
          3
        </span>
      </mwc-list-item>
    </mwc-select>
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.id]"
      label="id"
      maxlength="127"
      minlength="1"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[scl.cdc]"
      label="cdc"
      required=""
    >
    </wizard-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="add"
    label="[add]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot DOType wizards defines a createDOTypeWizard looks like the latest snapshot */

snapshots["DOType wizards defines a dOTypeWizard looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[dotype.wizard.title.edit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 48px)"
>
  <nav>
    <mwc-icon-button icon="more_vert">
    </mwc-icon-button>
    <mwc-menu
      class="actions-menu"
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
      >
        <span>
          [remove]
        </span>
        <mwc-icon slot="graphic">
          delete
        </mwc-icon>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
      >
        <span>
          [scl.DO]
        </span>
        <mwc-icon slot="graphic">
          playlist_add
        </mwc-icon>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
      >
        <span>
          [scl.DA]
        </span>
        <mwc-icon slot="graphic">
          playlist_add
        </mwc-icon>
      </mwc-list-item>
    </mwc-menu>
  </nav>
  <div id="wizard-content">
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.id]"
      label="id"
      maxlength="127"
      minlength="1"
      required=""
    >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
    <wizard-textfield
      helper="[scl.CDC]"
      label="CDC"
    >
    </wizard-textfield>
    <mwc-list style="margin-top: 0px;">
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="0"
        twoline=""
        value="#Dummy.LLN0.Mod>stVal"
      >
        <span>
          stVal
        </span>
        <span slot="secondary">
          #Dummy_Beh
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>q"
      >
        <span>
          q
        </span>
        <span slot="secondary">
          Quality
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>t"
      >
        <span>
          t
        </span>
        <span slot="secondary">
          Timestamp
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>stSeld"
      >
        <span>
          stSeld
        </span>
        <span slot="secondary">
          BOOLEAN
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>opRcvd"
      >
        <span>
          opRcvd
        </span>
        <span slot="secondary">
          BOOLEAN
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>opOk"
      >
        <span>
          opOk
        </span>
        <span slot="secondary">
          BOOLEAN
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>tOpOk"
      >
        <span>
          tOpOk
        </span>
        <span slot="secondary">
          Timestamp
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>ctlModel"
      >
        <span>
          ctlModel
        </span>
        <span slot="secondary">
          #Dummy_ctlModel
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>sboTimeout"
      >
        <span>
          sboTimeout
        </span>
        <span slot="secondary">
          INT32U
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>operTimeout"
      >
        <span>
          operTimeout
        </span>
        <span slot="secondary">
          INT32U
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>SBO"
      >
        <span>
          SBO
        </span>
        <span slot="secondary">
          ObjRef
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>SBOw"
      >
        <span>
          SBOw
        </span>
        <span slot="secondary">
          #Dummy.LLN0.Mod.SBOw
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>Oper"
      >
        <span>
          Oper
        </span>
        <span slot="secondary">
          #Dummy.LLN0.Mod.SBOw
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        class="DA"
        mwc-list-item=""
        tabindex="-1"
        twoline=""
        value="#Dummy.LLN0.Mod>Cancel"
      >
        <span>
          Cancel
        </span>
        <span slot="secondary">
          #Dummy.LLN0.Mod.Cancel
        </span>
      </mwc-list-item>
    </mwc-list>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon=""
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot DOType wizards defines a dOTypeWizard looks like the latest snapshot */

snapshots["DOType wizards defines a sDOWizard to edit an existing SDO looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[sdo.wizard.title.edit]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 48px)"
>
  <nav>
    <mwc-icon-button icon="more_vert">
    </mwc-icon-button>
    <mwc-menu
      class="actions-menu"
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
      >
        <span>
          [remove]
        </span>
        <mwc-icon slot="graphic">
          delete
        </mwc-icon>
      </mwc-list-item>
    </mwc-menu>
  </nav>
  <div id="wizard-content">
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.name]"
      label="name"
      required=""
    >
      >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
    <mwc-select
      fixedmenuposition=""
      helper="[scl.type]"
      label="type"
      required=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="0"
        value="Dummy.LLN0.Mod"
      >
        Dummy.LLN0.Mod
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LLN0.Beh"
      >
        Dummy.LLN0.Beh
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LLN0.Health"
      >
        Dummy.LLN0.Health
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LLN0.NamPlt"
      >
        Dummy.LLN0.NamPlt
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LPHD1.PhyNam"
      >
        Dummy.LPHD1.PhyNam
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LPHD1.Sim"
      >
        Dummy.LPHD1.Sim
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.XCBR1.Pos"
      >
        Dummy.XCBR1.Pos
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.CSWI.Pos1"
      >
        Dummy.CSWI.Pos1
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.CSWI.Pos2"
      >
        Dummy.CSWI.Pos2
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.XCBR1.OpCnt"
      >
        Dummy.XCBR1.OpCnt
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.XCBR1.NamPlt"
      >
        Dummy.XCBR1.NamPlt
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.XCBR1.BlkOpn"
      >
        Dummy.XCBR1.BlkOpn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.SPS"
      >
        Dummy.SPS
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.WYE"
      >
        Dummy.WYE
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        aria-selected="true"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="-1"
        value="Dummy.CMV"
      >
        Dummy.CMV
      </mwc-list-item>
    </mwc-select>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon=""
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot DOType wizards defines a sDOWizard to edit an existing SDO looks like the latest snapshot */

snapshots["DOType wizards defines a sDOWizard to create a new SDO element looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[sdo.wizard.title.add]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <wizard-textfield
      dialoginitialfocus=""
      helper="[scl.name]"
      label="name"
      required=""
    >
      >
    </wizard-textfield>
    <wizard-textfield
      disabled=""
      helper="[scl.desc]"
      label="desc"
      nullable=""
    >
    </wizard-textfield>
    <mwc-select
      fixedmenuposition=""
      helper="[scl.type]"
      label="type"
      required=""
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="0"
        value="Dummy.LLN0.Mod"
      >
        Dummy.LLN0.Mod
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LLN0.Beh"
      >
        Dummy.LLN0.Beh
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LLN0.Health"
      >
        Dummy.LLN0.Health
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LLN0.NamPlt"
      >
        Dummy.LLN0.NamPlt
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LPHD1.PhyNam"
      >
        Dummy.LPHD1.PhyNam
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.LPHD1.Sim"
      >
        Dummy.LPHD1.Sim
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.XCBR1.Pos"
      >
        Dummy.XCBR1.Pos
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.CSWI.Pos1"
      >
        Dummy.CSWI.Pos1
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.CSWI.Pos2"
      >
        Dummy.CSWI.Pos2
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.XCBR1.OpCnt"
      >
        Dummy.XCBR1.OpCnt
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.XCBR1.NamPlt"
      >
        Dummy.XCBR1.NamPlt
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.XCBR1.BlkOpn"
      >
        Dummy.XCBR1.BlkOpn
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.SPS"
      >
        Dummy.SPS
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.WYE"
      >
        Dummy.WYE
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="Dummy.CMV"
      >
        Dummy.CMV
      </mwc-list-item>
    </mwc-select>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon=""
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot DOType wizards defines a sDOWizard to create a new SDO element looks like the latest snapshot */

