/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["web component rendering Process element rendering LNode, GeneralEquipment,Function and ConductingEquipment children looks like the latest snapshot"] = 
`<action-pane
  label="ProcessGenConduct "
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Function"
      >
        <span>
          Function
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="ConductingEquipment"
      >
        <span>
          ConductingEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Substation"
      >
        <span>
          Substation
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Line"
      >
        <span>
          Line
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Process"
      >
        <span>
          Process
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <conducting-equipment-editor showfunctions="">
  </conducting-equipment-editor>
  <general-equipment-editor showfunctions="">
  </general-equipment-editor>
  <function-editor showfunctions="">
  </function-editor>
  <div class="container lnode">
    <l-node-editor>
    </l-node-editor>
  </div>
</action-pane>
`;
/* end snapshot web component rendering Process element rendering LNode, GeneralEquipment,Function and ConductingEquipment children looks like the latest snapshot */

snapshots["web component rendering Process element hides LNode and Function children looks like the latest snapshot"] = 
`<action-pane
  label="ProcessGenConduct "
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Function"
      >
        <span>
          Function
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="ConductingEquipment"
      >
        <span>
          ConductingEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Substation"
      >
        <span>
          Substation
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Line"
      >
        <span>
          Line
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Process"
      >
        <span>
          Process
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <conducting-equipment-editor>
  </conducting-equipment-editor>
  <general-equipment-editor>
  </general-equipment-editor>
</action-pane>
`;
/* end snapshot web component rendering Process element hides LNode and Function children looks like the latest snapshot */

snapshots["web component rendering Process element rendering Substation and Process children looks like the latest snapshot"] = 
`<action-pane
  label="ProcProcSubAA1 "
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Function"
      >
        <span>
          Function
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="ConductingEquipment"
      >
        <span>
          ConductingEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Substation"
      >
        <span>
          Substation
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Line"
      >
        <span>
          Line
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Process"
      >
        <span>
          Process
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <substation-editor showfunctions="">
  </substation-editor>
  <process-editor showfunctions="">
  </process-editor>
</action-pane>
`;
/* end snapshot web component rendering Process element rendering Substation and Process children looks like the latest snapshot */

snapshots["web component rendering Process element rendering a Line child looks like the latest snapshot"] = 
`<action-pane
  label="ProcessLine "
  tabindex="0"
>
  <abbr
    slot="action"
    title="[edit]"
  >
    <mwc-icon-button icon="edit">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    title="[remove]"
  >
    <mwc-icon-button icon="delete">
    </mwc-icon-button>
  </abbr>
  <abbr
    slot="action"
    style="position:relative;"
    title="[add]"
  >
    <mwc-icon-button icon="playlist_add">
    </mwc-icon-button>
    <mwc-menu
      corner="BOTTOM_RIGHT"
      menucorner="END"
    >
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="0"
        value="LNode"
      >
        <span>
          LNode
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="GeneralEquipment"
      >
        <span>
          GeneralEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Function"
      >
        <span>
          Function
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="ConductingEquipment"
      >
        <span>
          ConductingEquipment
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Substation"
      >
        <span>
          Substation
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Line"
      >
        <span>
          Line
        </span>
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        mwc-list-item=""
        role="menuitem"
        tabindex="-1"
        value="Process"
      >
        <span>
          Process
        </span>
      </mwc-list-item>
    </mwc-menu>
  </abbr>
  <line-editor showfunctions="">
  </line-editor>
</action-pane>
`;
/* end snapshot web component rendering Process element rendering a Line child looks like the latest snapshot */

