/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["Clone Redirection UI triggered by bay-editor looks like the latest snapshot"] = 
`<mwc-dialog
  heading="[substation.clone.redirect]"
  stacked=""
>
  <wizard-textfield
    label="[substation.clone.newname]"
    value="Q02"
  >
  </wizard-textfield>
  <mwc-select
    fixedmenuposition=""
    label="IED1"
    required=""
    value="no"
  >
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="no"
    >
      no
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED3"
    >
      IED3
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED4"
    >
      IED4
    </mwc-list-item>
  </mwc-select>
  <mwc-select
    fixedmenuposition=""
    label="IED2"
    required=""
    value="no"
  >
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="no"
    >
      no
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED3"
    >
      IED3
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED4"
    >
      IED4
    </mwc-list-item>
  </mwc-select>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    icon="content_copy"
    label="[substation.clone.cloneclose]"
    slot="primaryAction"
  >
  </mwc-button>
  <mwc-button
    icon="content_copy"
    label="[substation.clone.cloneproc]"
    slot="primaryAction"
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Clone Redirection UI triggered by bay-editor looks like the latest snapshot */

snapshots["Clone Redirection UI triggered by voltage-level-editor looks like the latest snapshot"] = 
`<mwc-dialog
  heading="[substation.clone.redirect]"
  stacked=""
>
  <wizard-textfield
    label="[substation.clone.newname]"
    value="E2"
  >
  </wizard-textfield>
  <mwc-select
    fixedmenuposition=""
    label="IED1"
    required=""
    value="no"
  >
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="no"
    >
      no
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED3"
    >
      IED3
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED4"
    >
      IED4
    </mwc-list-item>
  </mwc-select>
  <mwc-select
    fixedmenuposition=""
    label="IED2"
    required=""
    value="no"
  >
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="no"
    >
      no
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED3"
    >
      IED3
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED4"
    >
      IED4
    </mwc-list-item>
  </mwc-select>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    icon="content_copy"
    label="[substation.clone.cloneclose]"
    slot="primaryAction"
  >
  </mwc-button>
  <mwc-button
    icon="content_copy"
    label="[substation.clone.cloneproc]"
    slot="primaryAction"
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Clone Redirection UI triggered by voltage-level-editor looks like the latest snapshot */

snapshots["Clone Redirection UI triggered by substation-editor looks like the latest snapshot"] = 
`<mwc-dialog
  heading="[substation.clone.redirect]"
  stacked=""
>
  <wizard-textfield
    label="[substation.clone.newname]"
    value="AA2"
  >
  </wizard-textfield>
  <mwc-select
    fixedmenuposition=""
    label="IED1"
    required=""
    value="no"
  >
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="no"
    >
      no
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED3"
    >
      IED3
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED4"
    >
      IED4
    </mwc-list-item>
  </mwc-select>
  <mwc-select
    fixedmenuposition=""
    label="IED2"
    required=""
    value="no"
  >
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="no"
    >
      no
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED3"
    >
      IED3
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      mwc-list-item=""
      tabindex="-1"
      value="IED4"
    >
      IED4
    </mwc-list-item>
  </mwc-select>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    icon="content_copy"
    label="[substation.clone.cloneclose]"
    slot="primaryAction"
  >
  </mwc-button>
  <mwc-button
    icon="content_copy"
    label="[substation.clone.cloneproc]"
    slot="primaryAction"
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Clone Redirection UI triggered by substation-editor looks like the latest snapshot */

