/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["open-scd looks like its snapshot"] = 
`<oscd-waiter>
  <oscd-settings>
    <oscd-wizards>
      <mwc-drawer
        class="mdc-theme--surface"
        hasheader=""
        id="menu"
        type="modal"
      >
        <span slot="title">
          Menu
        </span>
        <mwc-list wrapfocus="">
          <li
            divider=""
            padded=""
            role="separator"
          >
          </li>
          <li
            divider=""
            padded=""
            role="separator"
          >
          </li>
          <li
            divider=""
            padded=""
            role="separator"
          >
          </li>
          <mwc-list-item
            aria-disabled="false"
            class="static"
            graphic="icon"
            iconid="settings"
            mwc-list-item=""
            tabindex="0"
          >
            <mwc-icon slot="graphic">
              settings
            </mwc-icon>
            <span>
              Settings
            </span>
          </mwc-list-item>
          <mwc-list-item
            aria-disabled="false"
            class="static"
            graphic="icon"
            iconid="extension"
            mwc-list-item=""
            tabindex="-1"
          >
            <mwc-icon slot="graphic">
              extension
            </mwc-icon>
            <span>
              Extensions
            </span>
          </mwc-list-item>
        </mwc-list>
        <mwc-top-app-bar-fixed slot="appContent">
          <mwc-icon-button
            icon="menu"
            label="Menu"
            slot="navigationIcon"
          >
          </mwc-icon-button>
          <div
            id="title"
            slot="title"
          >
          </div>
          <mwc-icon-button
            disabled=""
            icon="undo"
            label="undo"
            slot="actionItems"
          >
          </mwc-icon-button>
          <mwc-icon-button
            disabled=""
            icon="redo"
            label="redo"
            slot="actionItems"
          >
          </mwc-icon-button>
          <mwc-icon-button
            icon="list"
            label="menu.viewLog"
            slot="actionItems"
          >
          </mwc-icon-button>
          <mwc-icon-button
            icon="history"
            label="menu.viewHistory"
            slot="actionItems"
          >
          </mwc-icon-button>
          <mwc-icon-button
            icon="rule"
            label="menu.viewDiag"
            slot="actionItems"
          >
          </mwc-icon-button>
        </mwc-top-app-bar-fixed>
      </mwc-drawer>
      <div class="landing">
      </div>
      <mwc-dialog
        heading="Extensions"
        id="pluginManager"
        stacked=""
      >
        <mwc-list
          id="pluginList"
          multi=""
        >
          <mwc-list-item
            aria-disabled="false"
            graphic="avatar"
            noninteractive=""
            tabindex="-1"
          >
            <strong>
              Editor tab
            </strong>
            <mwc-icon
              class="inverted"
              slot="graphic"
            >
              tab
            </mwc-icon>
          </mwc-list-item>
          <li
            divider=""
            role="separator"
          >
          </li>
          <mwc-list-item
            aria-disabled="false"
            graphic="avatar"
            noninteractive=""
            tabindex="-1"
          >
            <strong>
              Menu entry
            </strong>
            <mwc-icon
              class="inverted"
              slot="graphic"
            >
              <strong>
                play_circle
              </strong>
            </mwc-icon>
          </mwc-list-item>
          <li
            divider=""
            role="separator"
          >
          </li>
          <li
            divider=""
            inset=""
            role="separator"
          >
          </li>
          <li
            divider=""
            inset=""
            role="separator"
          >
          </li>
          <li
            divider=""
            inset=""
            role="separator"
          >
          </li>
        </mwc-list>
        <mwc-button
          icon="refresh"
          label="Reset"
          slot="secondaryAction"
          style="--mdc-theme-primary: var(--mdc-theme-error)"
        >
        </mwc-button>
        <mwc-button
          dialogaction="close"
          icon=""
          label="Close"
          slot="secondaryAction"
        >
        </mwc-button>
        <mwc-button
          icon="library_add"
          label="Add custom extension…"
          outlined=""
          slot="primaryAction"
          trailingicon=""
        >
        </mwc-button>
      </mwc-dialog>
      <mwc-dialog
        heading="Add custom extension"
        id="pluginAdd"
      >
        <div style="display: flex; flex-direction: column; row-gap: 8px;">
          <p style="color:var(--mdc-theme-error);">
            Here you may add remote extensions directly from a custom URL.
                You do this at your own risk.
          </p>
          <mwc-textfield
            helper="Your preferred extension name"
            id="pluginNameInput"
            label="Name"
            required=""
          >
          </mwc-textfield>
          <mwc-list id="pluginKindList">
            <mwc-radio-list-item
              aria-disabled="false"
              aria-selected="true"
              graphic="control"
              hasmeta=""
              id="editor"
              left=""
              mwc-list-item=""
              selected=""
              tabindex="0"
              value="editor"
            >
              Editor tab
              <mwc-icon slot="meta">
                tab
              </mwc-icon>
            </mwc-radio-list-item>
            <mwc-radio-list-item
              aria-disabled="false"
              graphic="control"
              hasmeta=""
              id="menu"
              left=""
              mwc-list-item=""
              tabindex="-1"
              value="menu"
            >
              Menu entry
              <mwc-icon slot="meta">
                play_circle
              </mwc-icon>
            </mwc-radio-list-item>
            <div id="menudetails">
              <mwc-formfield
                id="enabledefault"
                label="Requires loaded document"
              >
                <mwc-switch
                  checked=""
                  id="requireDoc"
                >
                </mwc-switch>
              </mwc-formfield>
              <mwc-select
                fixedmenuposition=""
                id="menuPosition"
                value="middle"
              >
                <mwc-list-item
                  aria-disabled="false"
                  mwc-list-item=""
                  role="option"
                  tabindex="-1"
                  value="top"
                >
                  top
                </mwc-list-item>
                <mwc-list-item
                  activated=""
                  aria-disabled="false"
                  aria-selected="true"
                  mwc-list-item=""
                  role="option"
                  selected=""
                  tabindex="0"
                  value="middle"
                >
                  middle
                </mwc-list-item>
                <mwc-list-item
                  aria-disabled="false"
                  mwc-list-item=""
                  role="option"
                  tabindex="-1"
                  value="bottom"
                >
                  bottom
                </mwc-list-item>
              </mwc-select>
            </div>
            <mwc-radio-list-item
              aria-disabled="false"
              graphic="control"
              hasmeta=""
              id="validator"
              left=""
              mwc-list-item=""
              tabindex="-1"
              value="validator"
            >
              Validator
              <mwc-icon slot="meta">
                rule_folder
              </mwc-icon>
            </mwc-radio-list-item>
          </mwc-list>
          <mwc-textfield
            helper="The vendor supplied extension URL"
            id="pluginSrcInput"
            label="URL"
            placeholder="http://example.com/plugin.js"
            required=""
            type="url"
          >
          </mwc-textfield>
        </div>
        <mwc-button
          dialogaction="close"
          label="Cancel"
          slot="secondaryAction"
        >
        </mwc-button>
        <mwc-button
          icon="add"
          label="Add"
          slot="primaryAction"
          trailingicon=""
        >
        </mwc-button>
      </mwc-dialog>
      <mwc-dialog
        heading="Log"
        id="log"
      >
        <mwc-icon-button-toggle
          id="infofilter"
          on=""
        >
        </mwc-icon-button-toggle>
        <mwc-icon-button-toggle
          id="warningfilter"
          on=""
        >
        </mwc-icon-button-toggle>
        <mwc-icon-button-toggle
          id="errorfilter"
          on=""
        >
        </mwc-icon-button-toggle>
        <mwc-list
          id="content"
          wrapfocus=""
        >
          <mwc-list-item
            aria-disabled="true"
            disabled=""
            graphic="icon"
            mwc-list-item=""
            tabindex="0"
          >
            <span>
              Errors, warnings and other notifications will show up here.
            </span>
            <mwc-icon slot="graphic">
              info
            </mwc-icon>
          </mwc-list-item>
        </mwc-list>
        <mwc-button
          dialogaction="close"
          slot="primaryAction"
        >
          Close
        </mwc-button>
      </mwc-dialog>
      <mwc-dialog
        heading="SCL History"
        id="history"
      >
        <mwc-list
          id="content"
          wrapfocus=""
        >
          <mwc-list-item
            aria-disabled="true"
            disabled=""
            graphic="icon"
            mwc-list-item=""
            tabindex="0"
          >
            <span>
              Edits will show up here
            </span>
            <mwc-icon slot="graphic">
              info
            </mwc-icon>
          </mwc-list-item>
        </mwc-list>
        <mwc-button
          disabled=""
          icon="undo"
          label="Undo"
          slot="secondaryAction"
        >
        </mwc-button>
        <mwc-button
          disabled=""
          icon="redo"
          label="Redo"
          slot="secondaryAction"
        >
        </mwc-button>
        <mwc-button
          dialogaction="close"
          slot="primaryAction"
        >
          Close
        </mwc-button>
      </mwc-dialog>
      <mwc-dialog
        heading="Diagnostics"
        id="diagnostic"
      >
        <filtered-list
          id="content"
          wrapfocus=""
        >
          <mwc-list-item
            aria-disabled="true"
            disabled=""
            graphic="icon"
            mwc-list-item=""
            tabindex="0"
          >
            <span>
              Issues found during validation will show up here
            </span>
            <mwc-icon slot="graphic">
              info
            </mwc-icon>
          </mwc-list-item>
        </filtered-list>
        <mwc-button
          dialogaction="close"
          slot="primaryAction"
        >
          Close
        </mwc-button>
      </mwc-dialog>
      <mwc-snackbar
        id="info"
        labeltext="No errors"
        timeoutms="4000"
      >
        <mwc-icon-button
          icon="close"
          slot="dismiss"
        >
        </mwc-icon-button>
      </mwc-snackbar>
      <mwc-snackbar
        id="warning"
        labeltext="No errors"
        timeoutms="6000"
      >
        <mwc-button
          icon="history"
          slot="action"
        >
          Show
        </mwc-button>
        <mwc-icon-button
          icon="close"
          slot="dismiss"
        >
        </mwc-icon-button>
      </mwc-snackbar>
      <mwc-snackbar
        id="error"
        labeltext="No errors"
        timeoutms="10000"
      >
        <mwc-button
          icon="history"
          slot="action"
        >
          Show
        </mwc-button>
        <mwc-icon-button
          icon="close"
          slot="dismiss"
        >
        </mwc-icon-button>
      </mwc-snackbar>
      <mwc-snackbar
        id="issue"
        labeltext="No errors"
        timeoutms="10000"
      >
        <mwc-button
          icon="rule"
          slot="action"
        >
          Show
        </mwc-button>
        <mwc-icon-button
          icon="close"
          slot="dismiss"
        >
        </mwc-icon-button>
      </mwc-snackbar>
    </oscd-wizards>
  </oscd-settings>
</oscd-waiter>
`;
/* end snapshot open-scd looks like its snapshot */

