/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["create wizard for ConnectedAP element looks like the latest snapshot"] = 
`<mwc-dialog
  defaultaction="next"
  heading="[wizard.title.add]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <filtered-list
      id="apList"
      multi=""
    >
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="0"
        value="GOOSE_Publisher>AP2"
      >
        <span>
          GOOSE_Publisher>AP2
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Publisher>AP3"
      >
        <span>
          GOOSE_Publisher>AP3
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Publisher>AP4"
      >
        <span>
          GOOSE_Publisher>AP4
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Publisher2>AP1"
      >
        <span>
          GOOSE_Publisher2>AP1
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Publisher2>AP2"
      >
        <span>
          GOOSE_Publisher2>AP2
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Publisher2>AP3"
      >
        <span>
          GOOSE_Publisher2>AP3
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Publisher2>AP4"
      >
        <span>
          GOOSE_Publisher2>AP4
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Subscriber>AP1"
      >
        <span>
          GOOSE_Subscriber>AP1
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Subscriber>AP2"
      >
        <span>
          GOOSE_Subscriber>AP2
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="SMV_Publisher>AP1"
      >
        <span>
          SMV_Publisher>AP1
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="SMV_Publisher>AP3"
      >
        <span>
          SMV_Publisher>AP3
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="SMV_Publisher>AP4"
      >
        <span>
          SMV_Publisher>AP4
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="SMV_Publisher2>AP1"
      >
        <span>
          SMV_Publisher2>AP1
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="SMV_Publisher2>AP2"
      >
        <span>
          SMV_Publisher2>AP2
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="false"
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="SMV_Publisher2>AP3"
      >
        <span>
          SMV_Publisher2>AP3
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="true"
        disabled=""
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="GOOSE_Publisher>AP1"
      >
        <span>
          GOOSE_Publisher>AP1
        </span>
      </mwc-check-list-item>
      <mwc-check-list-item
        aria-disabled="true"
        disabled=""
        graphic="control"
        mwc-list-item=""
        tabindex="-1"
        value="SMV_Publisher>AP2"
      >
        <span>
          SMV_Publisher>AP2
        </span>
      </mwc-check-list-item>
    </filtered-list>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="save"
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot create wizard for ConnectedAP element looks like the latest snapshot */

