/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["Wizards for Locamation Plugin to edit the selected Logical Node -  starting screen as wizard -  looks like the latest snapshot"] =
`<mwc-dialog
  defaultaction="next"
  heading="[locamation.vmu.ln.editTitle]"
  open=""
  style="--mdc-dialog-min-width:calc(100% + 0px)"
>
  <div id="wizard-content">
    <locamation-ln-edit>
    </locamation-ln-edit>
  </div>
  <mwc-button
    dialogaction="close"
    label="[close]"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    icon="save"
    label="[save]"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot Wizards for Locamation Plugin to edit the selected Logical Node -  starting screen as wizard -  looks like the latest snapshot */

snapshots["Wizards for Locamation Plugin to edit the selected Logical Node -  using screen as web component with locamation LN for CIM (Channel) -  looks like the latest snapshot"] =
`<wizard-textfield
  disabled=""
  label="[locamation.vmu.ied.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.ldevice.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.ln.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.version]"
>
</wizard-textfield>
<wizard-textfield
  dialoginitialfocus=""
  helper="[locamation.vmu.identifierHelper]"
  id="identifier"
  label="[locamation.vmu.identifier]"
  pattern="^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\\.(?!$)|$)){3}$"
  placeholder="134.12.213"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.channelHelper]"
  id="channel"
  label="[locamation.vmu.channel]"
  pattern="[0-5]"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.transformPrimaryHelper]"
  id="transformPrimary"
  label="[locamation.vmu.transformPrimary]"
  pattern="[+]?[0-9]+(([.][0-9]*)?|([.][0-9]+))"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.transformSecondaryHelper]"
  id="transformSecondary"
  label="[locamation.vmu.transformSecondary]"
  pattern="[+]?[0-9]+(([.][0-9]*)?|([.][0-9]+))"
  required=""
>
</wizard-textfield>
`;
/* end snapshot Wizards for Locamation Plugin to edit the selected Logical Node -  using screen as web component with locamation LN for CIM (Channel) -  looks like the latest snapshot */

snapshots["Wizards for Locamation Plugin to edit the selected Logical Node -  using screen as web component with locamation LN for CIM (Sum) -  looks like the latest snapshot"] =
`<wizard-textfield
  disabled=""
  label="[locamation.vmu.ied.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.ldevice.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.ln.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.version]"
>
</wizard-textfield>
<wizard-textfield
  dialoginitialfocus=""
  helper="[locamation.vmu.identifierHelper]"
  id="identifier"
  label="[locamation.vmu.identifier]"
  pattern="^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\\.(?!$)|$)){3}$"
  placeholder="134.12.213"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.sumHelper]"
  id="sum"
  label="[locamation.vmu.sum]"
  pattern="[0-5],[0-5],[0-5]"
  placeholder="0,1,2"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.transformPrimaryHelper]"
  id="transformPrimary"
  label="[locamation.vmu.transformPrimary]"
  pattern="[+]?[0-9]+(([.][0-9]*)?|([.][0-9]+))"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.transformSecondaryHelper]"
  id="transformSecondary"
  label="[locamation.vmu.transformSecondary]"
  pattern="[+]?[0-9]+(([.][0-9]*)?|([.][0-9]+))"
  required=""
>
</wizard-textfield>
`;
/* end snapshot Wizards for Locamation Plugin to edit the selected Logical Node -  using screen as web component with locamation LN for CIM (Sum) -  looks like the latest snapshot */

snapshots["Wizards for Locamation Plugin to edit the selected Logical Node -  using screen as web component with locamation LN for VIM (Channel) -  looks like the latest snapshot"] =
`<wizard-textfield
  disabled=""
  label="[locamation.vmu.ied.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.ldevice.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.ln.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.version]"
>
</wizard-textfield>
<wizard-textfield
  dialoginitialfocus=""
  helper="[locamation.vmu.identifierHelper]"
  id="identifier"
  label="[locamation.vmu.identifier]"
  pattern="^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\\.(?!$)|$)){3}$"
  placeholder="134.12.213"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.channelHelper]"
  id="channel"
  label="[locamation.vmu.channel]"
  pattern="[0-2]"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.transformPrimaryHelper]"
  id="transformPrimary"
  label="[locamation.vmu.transformPrimary]"
  pattern="[+]?[0-9]+(([.][0-9]*)?|([.][0-9]+))"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.transformSecondaryHelper]"
  id="transformSecondary"
  label="[locamation.vmu.transformSecondary]"
  pattern="[+]?[0-9]+(([.][0-9]*)?|([.][0-9]+))"
  required=""
>
</wizard-textfield>
`;
/* end snapshot Wizards for Locamation Plugin to edit the selected Logical Node -  using screen as web component with locamation LN for VIM (Channel) -  looks like the latest snapshot */

snapshots["Wizards for Locamation Plugin to edit the selected Logical Node -  using screen as web component with locamation LN for VIM (Sum) -  looks like the latest snapshot"] =
`<wizard-textfield
  disabled=""
  label="[locamation.vmu.ied.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.ldevice.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.ln.name]"
>
</wizard-textfield>
<wizard-textfield
  disabled=""
  label="[locamation.vmu.version]"
>
</wizard-textfield>
<wizard-textfield
  dialoginitialfocus=""
  helper="[locamation.vmu.identifierHelper]"
  id="identifier"
  label="[locamation.vmu.identifier]"
  pattern="^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\\.(?!$)|$)){3}$"
  placeholder="134.12.213"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.sumHelper]"
  id="sum"
  label="[locamation.vmu.sum]"
  pattern="[0-2],[0-2],[0-2]"
  placeholder="0,1,2"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.transformPrimaryHelper]"
  id="transformPrimary"
  label="[locamation.vmu.transformPrimary]"
  pattern="[+]?[0-9]+(([.][0-9]*)?|([.][0-9]+))"
  required=""
>
</wizard-textfield>
<wizard-textfield
  helper="[locamation.vmu.transformSecondaryHelper]"
  id="transformSecondary"
  label="[locamation.vmu.transformSecondary]"
  pattern="[+]?[0-9]+(([.][0-9]*)?|([.][0-9]+))"
  required=""
>
</wizard-textfield>
`;
/* end snapshot Wizards for Locamation Plugin to edit the selected Logical Node -  using screen as web component with locamation LN for VIM (Sum) -  looks like the latest snapshot */

