on:
  push:
    branches:
      - main

permissions: 
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 14
          registry-url: 'http://registry.npmjs.org'
         
      - name: Install Dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: npm ci

      - name: Install core dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: npm i
        working-directory: lib/core

      - name: Build core
        if: ${{ steps.release.outputs.releases_created }}
        working-directory: lib/core
        run: npm run build

      - name: Install component dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: npm i
        working-directory: components/oscd-textfield

      - name: Build
        if: ${{ steps.release.outputs.releases_created }}
        run: npm run build:all

      - name: Publish to NPM
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx lerna publish from-package --no-push --no-private --force-publish --yes