/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["open-scd looks like its snapshot"] = 
`<mwc-drawer
  class="mdc-theme--surface"
  hasheader=""
  id="menu"
  type="modal"
>
  <span slot="title">
    Menu
  </span>
  <mwc-list wrapfocus="">
    <li
      divider=""
      padded=""
      role="separator"
    >
    </li>
    <mwc-list-item
      aria-disabled="false"
      class="top"
      graphic="icon"
      iconid="folder_open"
      mwc-list-item=""
      tabindex="0"
    >
      <mwc-icon slot="graphic">
        folder_open
      </mwc-icon>
      <span>
        Open project
      </span>
      <oscd-plugina2b400fc5f053cb1>
      </oscd-plugina2b400fc5f053cb1>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      class="top"
      graphic="icon"
      iconid="create_new_folder"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        create_new_folder
      </mwc-icon>
      <span>
        New project
      </span>
      <oscd-plugin679d81826289fb9a>
      </oscd-plugin679d81826289fb9a>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      class="top"
      disabled=""
      graphic="icon"
      iconid="save"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        save
      </mwc-icon>
      <span>
        Save project
      </span>
      <oscd-plugin1cb4a5367ff1f6a1>
      </oscd-plugin1cb4a5367ff1f6a1>
    </mwc-list-item>
    <li
      divider=""
      padded=""
      role="separator"
    >
    </li>
    <mwc-list-item
      aria-disabled="true"
      class="static"
      disabled=""
      graphic="icon"
      iconid="undo"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        undo
      </mwc-icon>
      <span>
        Undo
      </span>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      class="static"
      disabled=""
      graphic="icon"
      iconid="redo"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        redo
      </mwc-icon>
      <span>
        Redo
      </span>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      class="validator"
      disabled=""
      graphic="icon"
      iconid="rule_folder"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        rule_folder
      </mwc-icon>
      <span>
        Validate project
      </span>
      <oscd-plugin3aa68346726da1cd>
      </oscd-plugin3aa68346726da1cd>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      class="validator"
      disabled=""
      graphic="icon"
      iconid="rule_folder"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        rule_folder
      </mwc-icon>
      <span>
        Validate Templates
      </span>
      <oscd-plugin186320cdd626e422>
      </oscd-plugin186320cdd626e422>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      class="static"
      graphic="icon"
      iconid="history"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        history
      </mwc-icon>
      <span>
        View log
      </span>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      class="static"
      graphic="icon"
      iconid="rule"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        rule
      </mwc-icon>
      <span>
        View diagnostics
      </span>
    </mwc-list-item>
    <li
      divider=""
      padded=""
      role="separator"
    >
    </li>
    <mwc-list-item
      aria-disabled="true"
      class="middle"
      disabled=""
      graphic="icon"
      iconid="snippet_folder"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        snippet_folder
      </mwc-icon>
      <span>
        Import IEDs
      </span>
      <oscd-plugin4fed39e69404009b>
      </oscd-plugin4fed39e69404009b>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      class="middle"
      disabled=""
      graphic="icon"
      iconid="play_circle"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        play_circle
      </mwc-icon>
      <span>
        Subscriber Update
      </span>
      <oscd-plugin90bf5c90b69b347b>
      </oscd-plugin90bf5c90b69b347b>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      class="middle"
      disabled=""
      graphic="icon"
      iconid="merge_type"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        merge_type
      </mwc-icon>
      <span>
        Merge Project
      </span>
      <oscd-plugin2b4693cc19da2446>
      </oscd-plugin2b4693cc19da2446>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      class="middle"
      disabled=""
      graphic="icon"
      iconid="merge_type"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        merge_type
      </mwc-icon>
      <span>
        Update Substation
      </span>
      <oscd-plugin2a662bacb120083f>
      </oscd-plugin2a662bacb120083f>
    </mwc-list-item>
    <li
      divider=""
      padded=""
      role="separator"
    >
    </li>
    <mwc-list-item
      aria-disabled="false"
      class="static"
      graphic="icon"
      iconid="settings"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        settings
      </mwc-icon>
      <span>
        Settings
      </span>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="false"
      class="middle"
      graphic="icon"
      iconid="help"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        help
      </mwc-icon>
      <span>
        Help
      </span>
      <oscd-plugin48ab1a46d409bed9>
      </oscd-plugin48ab1a46d409bed9>
    </mwc-list-item>
    <li
      divider=""
      padded=""
      role="separator"
    >
    </li>
    <mwc-list-item
      aria-disabled="false"
      class="static"
      graphic="icon"
      iconid="extension"
      mwc-list-item=""
      tabindex="-1"
    >
      <mwc-icon slot="graphic">
        extension
      </mwc-icon>
      <span>
        Extensions
      </span>
    </mwc-list-item>
  </mwc-list>
  <mwc-top-app-bar-fixed slot="appContent">
    <mwc-icon-button
      icon="menu"
      label="Menu"
      slot="navigationIcon"
    >
    </mwc-icon-button>
    <div
      id="title"
      slot="title"
    >
    </div>
    <mwc-icon-button
      disabled=""
      icon="undo"
      label="undo"
      slot="actionItems"
    >
    </mwc-icon-button>
    <mwc-icon-button
      disabled=""
      icon="redo"
      label="redo"
      slot="actionItems"
    >
    </mwc-icon-button>
    <mwc-icon-button
      icon="history"
      label="menu.viewLog"
      slot="actionItems"
    >
    </mwc-icon-button>
    <mwc-icon-button
      icon="rule"
      label="menu.viewDiag"
      slot="actionItems"
    >
    </mwc-icon-button>
  </mwc-top-app-bar-fixed>
</mwc-drawer>
<div class="landing">
  <mwc-icon-button
    class="landing_icon"
    icon="folder_open"
  >
    <div class="landing_label">
      Open project
    </div>
  </mwc-icon-button>
  <mwc-icon-button
    class="landing_icon"
    icon="create_new_folder"
  >
    <div class="landing_label">
      New project
    </div>
  </mwc-icon-button>
</div>
<mwc-dialog
  heading="Log"
  id="log"
>
  <mwc-icon-button-toggle
    id="infofilter"
    on=""
  >
  </mwc-icon-button-toggle>
  <mwc-icon-button-toggle
    id="warningfilter"
    on=""
  >
  </mwc-icon-button-toggle>
  <mwc-icon-button-toggle
    id="errorfilter"
    on=""
  >
  </mwc-icon-button-toggle>
  <mwc-icon-button-toggle
    id="actionfilter"
    on=""
  >
  </mwc-icon-button-toggle>
  <mwc-icon-button-toggle id="sclhistoryfilter">
  </mwc-icon-button-toggle>
  <mwc-list
    id="content"
    wrapfocus=""
  >
    <mwc-list-item
      aria-disabled="true"
      disabled=""
      graphic="icon"
      mwc-list-item=""
      tabindex="0"
    >
      <span>
        Edits, errors, and other notifications will show up here.
      </span>
      <mwc-icon slot="graphic">
        info
      </mwc-icon>
    </mwc-list-item>
  </mwc-list>
  <mwc-button
    disabled=""
    icon="undo"
    label="Undo"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    disabled=""
    icon="redo"
    label="Redo"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    slot="primaryAction"
  >
    Close
  </mwc-button>
</mwc-dialog>
<mwc-dialog
  heading="Diagnostics"
  id="diagnostic"
>
  <filtered-list
    id="content"
    wrapfocus=""
  >
    <mwc-list-item
      aria-disabled="true"
      disabled=""
      graphic="icon"
      mwc-list-item=""
      tabindex="0"
    >
      <span>
        Issues found during validation will show up here
      </span>
      <mwc-icon slot="graphic">
        info
      </mwc-icon>
    </mwc-list-item>
  </filtered-list>
  <mwc-button
    dialogaction="close"
    slot="primaryAction"
  >
    Close
  </mwc-button>
</mwc-dialog>
<mwc-snackbar
  id="info"
  labeltext="No errors"
  timeoutms="4000"
>
  <mwc-icon-button
    icon="close"
    slot="dismiss"
  >
  </mwc-icon-button>
</mwc-snackbar>
<mwc-snackbar
  id="warning"
  labeltext="No errors"
  timeoutms="6000"
>
  <mwc-button
    icon="history"
    slot="action"
  >
    Show
  </mwc-button>
  <mwc-icon-button
    icon="close"
    slot="dismiss"
  >
  </mwc-icon-button>
</mwc-snackbar>
<mwc-snackbar
  id="error"
  labeltext="No errors"
  timeoutms="10000"
>
  <mwc-button
    icon="history"
    slot="action"
  >
    Show
  </mwc-button>
  <mwc-icon-button
    icon="close"
    slot="dismiss"
  >
  </mwc-icon-button>
</mwc-snackbar>
<mwc-snackbar
  id="issue"
  labeltext="No errors"
  timeoutms="10000"
>
  <mwc-button
    icon="rule"
    slot="action"
  >
    Show
  </mwc-button>
  <mwc-icon-button
    icon="close"
    slot="dismiss"
  >
  </mwc-icon-button>
</mwc-snackbar>
<mwc-dialog
  heading="Extensions"
  id="pluginManager"
  stacked=""
>
  <mwc-list
    id="pluginList"
    multi=""
  >
    <mwc-list-item
      aria-disabled="false"
      graphic="avatar"
      noninteractive=""
      tabindex="-1"
    >
      <strong>
        Editor tab
      </strong>
      <mwc-icon
        class="inverted"
        slot="graphic"
      >
        tab
      </mwc-icon>
    </mwc-list-item>
    <li
      divider=""
      role="separator"
    >
    </li>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="0"
      value="/src/editors/Substation.js"
    >
      <mwc-icon slot="meta">
        margin
      </mwc-icon>
      Substation
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      tabindex="-1"
      value="/src/editors/IED.js"
    >
      <mwc-icon slot="meta">
        developer_board
      </mwc-icon>
      IED
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      tabindex="-1"
      value="/src/editors/SingleLineDiagram.js"
    >
      <mwc-icon slot="meta">
        edit
      </mwc-icon>
      Single Line Diagram
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/editors/Subscription.js"
    >
      <mwc-icon slot="meta">
        link
      </mwc-icon>
      Subscription
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/editors/SampledValues.js"
    >
      <mwc-icon slot="meta">
        link
      </mwc-icon>
      Sampled Values Subscriber
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/editors/Communication.js"
    >
      <mwc-icon slot="meta">
        settings_ethernet
      </mwc-icon>
      Communication
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/editors/Templates.js"
    >
      <mwc-icon slot="meta">
        copy_all
      </mwc-icon>
      Templates
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/editors/TemplatesProt.js"
    >
      <mwc-icon slot="meta">
        copy_all
      </mwc-icon>
      Templates2
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      tabindex="-1"
      value="/src/editors/Cleanup.js"
    >
      <mwc-icon slot="meta">
        cleaning_services
      </mwc-icon>
      Cleanup
    </mwc-check-list-item>
    <mwc-list-item
      aria-disabled="false"
      graphic="avatar"
      noninteractive=""
      tabindex="-1"
    >
      <strong>
        Menu entry
      </strong>
      <mwc-icon
        class="inverted"
        slot="graphic"
      >
        <strong>
          play_circle
        </strong>
      </mwc-icon>
    </mwc-list-item>
    <li
      divider=""
      role="separator"
    >
    </li>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/menu/OpenProject.js"
    >
      <mwc-icon slot="meta">
        folder_open
      </mwc-icon>
      Open project
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/menu/NewProject.js"
    >
      <mwc-icon slot="meta">
        create_new_folder
      </mwc-icon>
      New project
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/menu/SaveProject.js"
    >
      <mwc-icon slot="meta">
        save
      </mwc-icon>
      Save project
    </mwc-check-list-item>
    <li
      divider=""
      inset=""
      role="separator"
    >
    </li>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/validators/ValidateSchema.js"
    >
      <mwc-icon slot="meta">
        rule_folder
      </mwc-icon>
      Validate project
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/validators/ValidateTemplates.js"
    >
      <mwc-icon slot="meta">
        rule_folder
      </mwc-icon>
      Validate Templates
    </mwc-check-list-item>
    <li
      divider=""
      inset=""
      role="separator"
    >
    </li>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/menu/ImportIEDs.js"
    >
      <mwc-icon slot="meta">
        snippet_folder
      </mwc-icon>
      Import IEDs
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/menu/SubscriberInfo.js"
    >
      <mwc-icon slot="meta">
        play_circle
      </mwc-icon>
      Subscriber Update
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      tabindex="-1"
      value="/src/menu/UpdateDescriptionABB.js"
    >
      <mwc-icon slot="meta">
        play_circle
      </mwc-icon>
      Update desc (ABB)
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      tabindex="-1"
      value="/src/menu/UpdateDescriptionSEL.js"
    >
      <mwc-icon slot="meta">
        play_circle
      </mwc-icon>
      Update desc (SEL)
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/menu/Merge.js"
    >
      <mwc-icon slot="meta">
        merge_type
      </mwc-icon>
      Merge Project
    </mwc-check-list-item>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/menu/UpdateSubstation.js"
    >
      <mwc-icon slot="meta">
        merge_type
      </mwc-icon>
      Update Substation
    </mwc-check-list-item>
    <li
      divider=""
      inset=""
      role="separator"
    >
    </li>
    <mwc-check-list-item
      aria-disabled="false"
      class="official"
      graphic="control"
      hasmeta=""
      left=""
      mwc-list-item=""
      selected=""
      tabindex="-1"
      value="/src/menu/Help.js"
    >
      <mwc-icon slot="meta">
        help
      </mwc-icon>
      Help
    </mwc-check-list-item>
  </mwc-list>
  <mwc-button
    icon="refresh"
    label="Reset"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
  </mwc-button>
  <mwc-button
    dialogaction="close"
    icon=""
    label="Close"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    icon="library_add"
    label="Add custom extension…"
    outlined=""
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
<mwc-dialog
  heading="Add custom extension"
  id="pluginAdd"
>
  <div style="display: flex; flex-direction: column; row-gap: 8px;">
    <p style="color:var(--mdc-theme-error);">
      Here you may add remote extensions directly from a custom URL.
                You do this at your own risk.
    </p>
    <mwc-textfield
      helper="Your preferred extension name"
      id="pluginNameInput"
      label="Name"
      required=""
    >
    </mwc-textfield>
    <mwc-list id="pluginKindList">
      <mwc-radio-list-item
        aria-disabled="false"
        aria-selected="true"
        graphic="control"
        hasmeta=""
        id="editor"
        left=""
        mwc-list-item=""
        selected=""
        tabindex="0"
        value="editor"
      >
        Editor tab
        <mwc-icon slot="meta">
          tab
        </mwc-icon>
      </mwc-radio-list-item>
      <mwc-radio-list-item
        aria-disabled="false"
        graphic="control"
        hasmeta=""
        id="menu"
        left=""
        mwc-list-item=""
        tabindex="-1"
        value="menu"
      >
        Menu entry
        <mwc-icon slot="meta">
          play_circle
        </mwc-icon>
      </mwc-radio-list-item>
      <div id="menudetails">
        <mwc-formfield
          id="enabledefault"
          label="Requires loaded document"
        >
          <mwc-switch
            checked=""
            id="requireDoc"
          >
          </mwc-switch>
        </mwc-formfield>
        <mwc-select
          fixedmenuposition=""
          id="menuPosition"
          value="middle"
        >
          <mwc-list-item
            aria-disabled="false"
            mwc-list-item=""
            role="option"
            tabindex="-1"
            value="top"
          >
            top
          </mwc-list-item>
          <mwc-list-item
            activated=""
            aria-disabled="false"
            aria-selected="true"
            mwc-list-item=""
            role="option"
            selected=""
            tabindex="0"
            value="middle"
          >
            middle
          </mwc-list-item>
          <mwc-list-item
            aria-disabled="false"
            mwc-list-item=""
            role="option"
            tabindex="-1"
            value="bottom"
          >
            bottom
          </mwc-list-item>
        </mwc-select>
      </div>
      <mwc-radio-list-item
        aria-disabled="false"
        graphic="control"
        hasmeta=""
        id="validator"
        left=""
        mwc-list-item=""
        tabindex="-1"
        value="validator"
      >
        Validator
        <mwc-icon slot="meta">
          rule_folder
        </mwc-icon>
      </mwc-radio-list-item>
    </mwc-list>
    <mwc-textfield
      helper="The vendor supplied extension URL"
      id="pluginSrcInput"
      label="URL"
      placeholder="http://example.com/plugin.js"
      required=""
      type="url"
    >
    </mwc-textfield>
  </div>
  <mwc-button
    dialogaction="close"
    label="Cancel"
    slot="secondaryAction"
  >
  </mwc-button>
  <mwc-button
    icon="add"
    label="Add"
    slot="primaryAction"
    trailingicon=""
  >
  </mwc-button>
</mwc-dialog>
<mwc-circular-progress-four-color
  closed=""
  density="0"
  indeterminate=""
  progress="0"
>
</mwc-circular-progress-four-color>
<wizard-dialog>
</wizard-dialog>
<mwc-dialog
  heading="Settings"
  id="settings"
>
  <form>
    <mwc-select
      fixedmenuposition=""
      icon="language"
      id="language"
      label="Language"
    >
      <mwc-list-item
        aria-disabled="false"
        aria-selected="true"
        graphic="icon"
        mwc-list-item=""
        role="option"
        selected=""
        tabindex="0"
        value="en"
      >
        English
      </mwc-list-item>
      <mwc-list-item
        aria-disabled="false"
        graphic="icon"
        mwc-list-item=""
        role="option"
        tabindex="-1"
        value="de"
      >
        German (Deutsch)
      </mwc-list-item>
    </mwc-select>
    <mwc-formfield label="Dark theme">
      <mwc-switch id="dark">
      </mwc-switch>
    </mwc-formfield>
    <mwc-formfield label="Pro mode">
      <mwc-switch id="mode">
      </mwc-switch>
    </mwc-formfield>
    <mwc-formfield label="Show IEDs in substation editor">
      <mwc-switch id="showieds">
      </mwc-switch>
    </mwc-formfield>
  </form>
  <wizard-divider>
  </wizard-divider>
  <section>
    <h3>
      Uploaded NSDoc files
    </h3>
    <input
      accept=".nsdoc"
      hidden=""
      id="nsdoc-file"
      multiple=""
      required=""
      type="file"
    >
    <mwc-button
      id="selectFileButton"
      label="Select file"
    >
    </mwc-button>
  </section>
  <mwc-list id="nsdocList">
    <mwc-list-item
      aria-disabled="true"
      disabled=""
      graphic="avatar"
      hasmeta=""
      id="IEC 61850-7-2"
      mwc-list-item=""
      tabindex="0"
      twoline=""
    >
      <span>
        IEC 61850-7-2
      </span>
      <mwc-icon
        slot="graphic"
        style="color:red;"
      >
        close
      </mwc-icon>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      disabled=""
      graphic="avatar"
      hasmeta=""
      id="IEC 61850-7-3"
      mwc-list-item=""
      tabindex="-1"
      twoline=""
    >
      <span>
        IEC 61850-7-3
      </span>
      <mwc-icon
        slot="graphic"
        style="color:red;"
      >
        close
      </mwc-icon>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      disabled=""
      graphic="avatar"
      hasmeta=""
      id="IEC 61850-7-4"
      mwc-list-item=""
      tabindex="-1"
      twoline=""
    >
      <span>
        IEC 61850-7-4
      </span>
      <mwc-icon
        slot="graphic"
        style="color:red;"
      >
        close
      </mwc-icon>
    </mwc-list-item>
    <mwc-list-item
      aria-disabled="true"
      disabled=""
      graphic="avatar"
      hasmeta=""
      id="IEC 61850-8-1"
      mwc-list-item=""
      tabindex="-1"
      twoline=""
    >
      <span>
        IEC 61850-8-1
      </span>
      <mwc-icon
        slot="graphic"
        style="color:red;"
      >
        close
      </mwc-icon>
    </mwc-list-item>
  </mwc-list>
  <mwc-button
    dialogaction="close"
    slot="secondaryAction"
  >
    Cancel
  </mwc-button>
  <mwc-button
    dialogaction="reset"
    slot="secondaryAction"
    style="--mdc-theme-primary: var(--mdc-theme-error)"
  >
    Reset
  </mwc-button>
  <mwc-button
    dialogaction="save"
    icon="save"
    slot="primaryAction"
    trailingicon=""
  >
    Save
  </mwc-button>
</mwc-dialog>
`;
/* end snapshot open-scd looks like its snapshot */

